--------------------------------------------------------
--  DDL for Table ANTIBODIES_STAGING
--------------------------------------------------------

  CREATE TABLE "WEB"."ANTIBODIES_STAGING" 
   (	"SEQ_NO" NUMBER, 
	"ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ANTIBODY_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_URL" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"IMAGE_URL" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"CLONE" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"SHORT_DESCRIPTION" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"FULL_DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"FULL_ANTIBODY_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"BRAND" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"HOST" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ANTIBODY_TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"APPLICATION_CATEGORIES" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTROL" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"DILUTION_RANGE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"REACTIVITY" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"VISUALIZATION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"DELETED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
