--------------------------------------------------------
--  DDL for Table ANTIBODIES
--------------------------------------------------------

  CREATE TABLE "WEB"."ANTIBODIES" 
   (	"SEQ_NO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 382 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ANTIBODY_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_URL" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"IMAGE_URL" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"CLONE" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"SHORT_DESCRIPTION" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"FULL_DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"FULL_ANTIBODY_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"BRAND" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"HOST" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ANTIBODY_TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"APPLICATION_CATEGORIES" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTROL" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"DILUTION_RANGE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"REACTIVITY" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"VISUALIZATION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"DELETED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
