--------------------------------------------------------
--  DDL for Table DISCIPLINE
--------------------------------------------------------

  CREATE TABLE "WEB"."DISCIPLINE" 
   (	"DELETED" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"DISCIPLINE_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DISCIPLINE_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DISCIPLINE_ICON_CLASS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DISCIPLINE_ORDER" NUMBER, 
	"DATE_CREATED" DATE DEFAULT SYSDATE, 
	"DATE_DELETED" DATE, 
	"ANCHOR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DISCIPLINE_IMAGE_1" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"DISCIPLINE_IMAGE_2" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
