--------------------------------------------------------
--  Constraints for Table DISCIPLINE
--------------------------------------------------------

  ALTER TABLE "WEB"."DISCIPLINE" MODIFY ("DISCIPLINE_ID" NOT NULL ENABLE);
  ALTER TABLE "WEB"."DISCIPLINE" MODIFY ("DISCIPLINE_NAME" NOT NULL ENABLE);
  ALTER TABLE "WEB"."DISCIPLINE" ADD CHECK (deleted IN ('Y', 'N')) ENABLE;
  ALTER TABLE "WEB"."DISCIPLINE" ADD CHECK (active IN ('Y', 'N')) ENABLE;
  ALTER TABLE "WEB"."DISCIPLINE" ADD CONSTRAINT "PK_DISCIPLINE" PRIMARY KEY ("DISCIPLINE_ID")
  USING INDEX "WEB"."PK_DISCIPLINE"  ENABLE;
