--------------------------------------------------------
--  Constraints for Table FACET_SCOPE
--------------------------------------------------------

  ALTER TABLE "WEB"."FACET_SCOPE" MODIFY ("FACET_SCOPE_ID" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_SCOPE" MODIFY ("FACET_ID" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_SCOPE" MODIFY ("SCOPE_PRIORITY" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_SCOPE" MODIFY ("DISPLAY_ORDER" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_SCOPE" MODIFY ("VISIBLE_YN" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_SCOPE" MODIFY ("ACTIVE_YN" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_SCOPE" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_SCOPE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_SCOPE" ADD CONSTRAINT "CK_FACET_SCOPE_VISIBLE" CHECK (VISIBLE_YN in ('Y','N')) ENABLE;
  ALTER TABLE "WEB"."FACET_SCOPE" ADD CONSTRAINT "CK_FACET_SCOPE_ACTIVE" CHECK (ACTIVE_YN in ('Y','N')) ENABLE;
  ALTER TABLE "WEB"."FACET_SCOPE" ADD PRIMARY KEY ("FACET_SCOPE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
