--------------------------------------------------------
--  Constraints for Table FACET_DEFINITION
--------------------------------------------------------

  ALTER TABLE "WEB"."FACET_DEFINITION" MODIFY ("FACET_ID" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_DEFINITION" MODIFY ("FACET_CODE" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_DEFINITION" MODIFY ("FACET_LABEL" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_DEFINITION" MODIFY ("VALUE_DATA_TYPE" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_DEFINITION" MODIFY ("IS_MULTI_VALUE" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_DEFINITION" MODIFY ("DISPLAY_ORDER" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_DEFINITION" MODIFY ("ACTIVE_YN" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_DEFINITION" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_DEFINITION" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WEB"."FACET_DEFINITION" ADD CONSTRAINT "CK_FACET_DEF_MULTI" CHECK (IS_MULTI_VALUE in ('Y','N')) ENABLE;
  ALTER TABLE "WEB"."FACET_DEFINITION" ADD CONSTRAINT "CK_FACET_DEF_ACTIVE" CHECK (ACTIVE_YN in ('Y','N')) ENABLE;
  ALTER TABLE "WEB"."FACET_DEFINITION" ADD PRIMARY KEY ("FACET_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "WEB"."FACET_DEFINITION" ADD CONSTRAINT "UQ_FACET_DEF_CODE" UNIQUE ("FACET_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
