--------------------------------------------------------
--  File created - Tuesday-May-19-2026   
--------------------------------------------------------
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\DBTOOLS_EXECUTION_HISTORY_SEQ.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_WEBSITE_MESSAGE_SEQ.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\ANTIBODIES.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\ANTIBODIES_STAGING.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\DISCIPLINE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\FACET_DEFINITION.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\FACET_SCOPE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_ITEMS.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_ITEMS_29APR2026.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_ITEMS_EXTRACT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_ITEMS_STAGED.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_TEMP.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MMQCI_PRODUCTS.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_BACKUP_24APR2026.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_MMQCI.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_RELATED.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_STAGING.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_VAZYME.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_CANONICAL_XREF.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_FACET_VALUE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_GROUP.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_TYPE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SUPPLIERS.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SUPPLIERS_STAGING.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_CONFIG.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_DIVISIONS.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_JOB_TITLES.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_MESSAGES.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_MESSAGE_ENQUIRY_TYPE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_MESSAGE_TYPES.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_SOURCES.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_USERS.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\DISCIPLINE_PRODUCT_GROUP_VIEW.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_VIEW_ALL.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\VW_ANTIBODY_APPLICATION_CATEGORIES.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\VW_PRODUCT_ANTIBODY_FACETS_COMPAT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\ANTIBODIES_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\ANTIBODIES_STAGING_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\DISCIPLINE_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\FACET_DEFINITION_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\FACET_SCOPE_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_ITEMS_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_ITEMS_29APR2026_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_ITEMS_EXTRACT_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_ITEMS_STAGED_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_TEMP_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MMQCI_PRODUCTS_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_BACKUP_24APR2026_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_MMQCI_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_RELATED_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_STAGING_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_VAZYME_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_CANONICAL_XREF_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_FACET_VALUE_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_GROUP_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_TYPE_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SUPPLIERS_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SUPPLIERS_STAGING_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_CONFIG_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_DIVISIONS_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_JOB_TITLES_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_MESSAGES_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_MESSAGE_ENQUIRY_TYPE_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_MESSAGE_TYPES_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_SOURCES_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_USERS_DATA_TABLE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_ITEMS_IX2.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_ITEMS_IX3.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PK_PRODUCTS.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\IX_FACET_SCOPE_LOOKUP.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\UQ_FACET_DEF_CODE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\UQ_PROD_XREF_SOURCE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PK_PRODUCT_GROUP.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\IX_PROD_FACET_LOOKUP.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_GROUP_IX1.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\UQ_PROD_FACET.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\UQ_PROD_XREF_CANON.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PK_PRODUCTS_RELATED.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\IX_PROD_XREF_CANON.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\UX_PRODUCTS_SUPP_SUPP_PROD_ID.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_TYPE_IX1.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PK_DISCIPLINE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\DISCIPLINE_IX1.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_ITEMS_IX1.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PK_PRODUCT_TYPE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PK_SUPPLIERS.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_RELATED_IX1.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_DETAILS_RELATED_PRODUCTS_PROC.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SENDGRID_SEND_EMAIL.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\ANTIBODY_CONTACT_US_DRAWER.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\BUILD_WORKSPACE_FILE_URL.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\CONTACT_US_GENERAL.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\FILE_URL_EXTERNAL.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\GENERATE_FOOTER.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\GENERATE_FOOTER_DESKTOP.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\GENERATE_FOOTER_MOBILE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\GENERATE_MEGA_MENU.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\GENERATE_MEGA_MENU_DESKTOP.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\GENERATE_MEGA_MENU_MOBILE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\GENERATE_MENU_NAV_UL_LI.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\GENERATE_MENU_NAV_UL_LI_DESKTOP.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\GENERATE_MENU_NAV_UL_LI_DESKTOP_29APR2026.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\GENERATE_MENU_NAV_UL_LI_DESKTOP_30mar2026.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\GENERATE_MENU_NAV_UL_LI_MOBILE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\GENERATE_MENU_SITEMAP_UL_LI.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\GET_ANCHOR_ID.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\GET_MENU_INFO.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\GET_STATIC_VERSION.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_CONTACT_US_DRAWER.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_DETAIL0.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_DETAILS.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_DETAILS1.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_DETAILS_DISPLAY.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_DETAILS_DISPLAY_DRAWER.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_DETAILS_RELATED_DISPLAY.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_IMAGE_DISPLAY.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_RELATED_DETAILS.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_RELATED_SLIDER.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\RENDER_MENU_UL_DESKTOP.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\RENDER_MENU_UL_MOBILE.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SUPPLIER_GRID.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_PAGE_URL.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_ITEMS_EXTRACT_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_MESSAGES_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_ITEMS_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_STAGING_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_TYPE_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\FACET_DEFINITION_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_GROUP_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_SOURCES_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_MESSAGE_ENQUIRY_TYPE_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_USERS_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\ANTIBODIES_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_TEMP_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_CANONICAL_XREF_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_MESSAGE_TYPES_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_ITEMS_STAGED_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_FACET_VALUE_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_DIVISIONS_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\DISCIPLINE_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_RELATED_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MENU_ITEMS_29APR2026_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\MMQCI_PRODUCTS_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_MMQCI_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_JOB_TITLES_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\ANTIBODIES_STAGING_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\FACET_SCOPE_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCTS_BACKUP_24APR2026_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SUPPLIERS_STAGING_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_CONFIG_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SUPPLIERS_CONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\FACET_SCOPE_REFCONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\PRODUCT_FACET_VALUE_REFCONSTRAINT.sql
@C:\Websites\Syntec_ReactPHP\Oracle_Exports\SYNTEC_MESSAGES_REFCONSTRAINT.sql
