--------------------------------------------------------
--  DDL for Index IX_FACET_SCOPE_LOOKUP
--------------------------------------------------------

  CREATE INDEX "WEB"."IX_FACET_SCOPE_LOOKUP" ON "WEB"."FACET_SCOPE" ("ACTIVE_YN", "WEBSITE_NAME", "DIAGNOSTIC_ID", "CATEGORY_ID", "PRODUCT_LINE_ID", "SUPPLIER_ID", "DISPLAY_ORDER") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
