--------------------------------------------------------
--  DDL for Index IX_PROD_FACET_LOOKUP
--------------------------------------------------------

  CREATE INDEX "WEB"."IX_PROD_FACET_LOOKUP" ON "WEB"."PRODUCT_FACET_VALUE" ("FACET_ID", "ACTIVE_YN", "FACET_VALUE_NORM", "CANONICAL_PRODUCT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 158 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
