--------------------------------------------------------
--  DDL for Index MENU_ITEMS_IX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEB"."MENU_ITEMS_IX1" ON "WEB"."MENU_ITEMS" ("MENU_ID", "SUB_MENU_LEVEL_ID", "SUB_MENU_ID", "MENU_ORDER") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
