--------------------------------------------------------
--  DDL for Table MENU_ITEMS_STAGED
--------------------------------------------------------

  CREATE TABLE "WEB"."MENU_ITEMS_STAGED" 
   (	"MENU_ID" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"MENU_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SUB_MENU_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PARENT_ID" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"URL" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ICON_CLASS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CLASS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SUB_MENU_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"BUSINESS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MENU_ORDER" NUMBER, 
	"WEBSITE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"WEBSITE_SET" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"WEBSITE_ANCHOR" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SUB_MENU_LEVEL_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"SUB_MENU_TEXT" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"MENU_ID_ORDER" NUMBER, 
	"BUSINESS_SET" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DISCIPLINE_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_GROUP_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ENABLED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"URL_MOBILE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"MENU_ORDER_CLONE" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
