--------------------------------------------------------
--  DDL for Table MMQCI_PRODUCTS
--------------------------------------------------------

  CREATE TABLE "WEB"."MMQCI_PRODUCTS" 
   (	"PRODUCT_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PART_NUMBER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_GROUP" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"KIT_CONFIGURATION" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"DETAILS" CLOB COLLATE "USING_NLS_COMP", 
	"PRODUCT_LINK" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"PRICE_USD" NUMBER(10,2), 
	"IMAGE_FILENAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 LOB ("DETAILS") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
