--------------------------------------------------------
--  Constraints for Table PRODUCT_CANONICAL_XREF
--------------------------------------------------------

  ALTER TABLE "WEB"."PRODUCT_CANONICAL_XREF" MODIFY ("PRODUCT_XREF_ID" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_CANONICAL_XREF" MODIFY ("SOURCE_SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_CANONICAL_XREF" MODIFY ("SOURCE_KEY" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_CANONICAL_XREF" MODIFY ("CANONICAL_PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_CANONICAL_XREF" MODIFY ("ACTIVE_YN" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_CANONICAL_XREF" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_CANONICAL_XREF" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_CANONICAL_XREF" ADD CONSTRAINT "CK_PROD_XREF_ACTIVE" CHECK (ACTIVE_YN in ('Y','N')) ENABLE;
  ALTER TABLE "WEB"."PRODUCT_CANONICAL_XREF" ADD PRIMARY KEY ("PRODUCT_XREF_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "WEB"."PRODUCT_CANONICAL_XREF" ADD CONSTRAINT "UQ_PROD_XREF_SOURCE" UNIQUE ("SOURCE_SYSTEM", "SOURCE_KEY")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "WEB"."PRODUCT_CANONICAL_XREF" ADD CONSTRAINT "UQ_PROD_XREF_CANON" UNIQUE ("SOURCE_SYSTEM", "CANONICAL_PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
