--------------------------------------------------------
--  Constraints for Table PRODUCTS_RELATED
--------------------------------------------------------

  ALTER TABLE "WEB"."PRODUCTS_RELATED" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCTS_RELATED" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCTS_RELATED" MODIFY ("PRODUCT_RELATED_ID" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCTS_RELATED" MODIFY ("PRODUCT_RELATED_NAME" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCTS_RELATED" ADD CHECK (deleted IN ('Y', 'N')) ENABLE;
  ALTER TABLE "WEB"."PRODUCTS_RELATED" ADD CHECK (active IN ('Y', 'N')) ENABLE;
  ALTER TABLE "WEB"."PRODUCTS_RELATED" ADD CONSTRAINT "PK_PRODUCTS_RELATED" PRIMARY KEY ("PRODUCT_ID", "PRODUCT_RELATED_ID")
  USING INDEX "WEB"."PK_PRODUCTS_RELATED"  ENABLE;
