--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "WEB"."PRODUCTS" 
   (	"DELETED" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"PRODUCT_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_NAME_WEB" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SHORT_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_SIPPLIER_ORDER" NUMBER, 
	"SUPPLIER_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DISCIPLINE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_GROUP" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CLASS_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CLASS_COLOUR" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ABOUT_1" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"ABOUT_2" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_LINK" VARCHAR2(800 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_ENQUIRE" VARCHAR2(800 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_IMAGE_LARGE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_IMAGE_SMALL" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_IMAGE_1" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_IMAGE_2" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_IMAGE_3" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_IMAGE_4" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_PARENT_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DATE_CREATED" DATE DEFAULT SYSDATE, 
	"DATE_DELETED" DATE, 
	"ANCHOR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_IMAGE_LARGE_WIDTH" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_IMAGE_LARGE_HEIGHT" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_IMAGE_SMALL_WIDTH" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_IMAGE_SMALL_HEIGHT" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DISCIPLINE_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_GROUP_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_TYPE_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_GROUP_TYPE_ALT" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_GROUP_TYPE_ALT_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"BUSINESS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_IMAGE_EXTERNAL" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"PROUDUCT_SKU" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_PRODUCT_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
