--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "WEB"."PRODUCTS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCTS" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCTS" ADD CHECK (deleted IN ('Y', 'N')) ENABLE;
  ALTER TABLE "WEB"."PRODUCTS" ADD CHECK (active IN ('Y', 'N')) ENABLE;
  ALTER TABLE "WEB"."PRODUCTS" ADD CONSTRAINT "PK_PRODUCTS" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX "WEB"."PK_PRODUCTS"  ENABLE;
  ALTER TABLE "WEB"."PRODUCTS" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
