--------------------------------------------------------
--  DDL for Table PRODUCTS_RELATED
--------------------------------------------------------

  CREATE TABLE "WEB"."PRODUCTS_RELATED" 
   (	"DELETED" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"PRODUCT_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_RELATED_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_RELATED_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_TYPE_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DATE_CREATED" DATE DEFAULT SYSDATE, 
	"DATE_DELETED" DATE, 
	"SORT_ORDER" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
