--------------------------------------------------------
--  DDL for View PRODUCTS_VIEW_ALL
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WEB"."PRODUCTS_VIEW_ALL" ("PRODUCT_BUSINESS", "PRODUCT_TYPE", "DISCIPLINE", "DISCIPLINE_ID", "PRODUCT_GROUP", "PRODUCT_GROUP_ID", "PRODUCT_GROUP_TYPE_ALT_ID", "PRODUCT_GROUP_TYPE_ALT", "SUPPLIER_ID", "SUPPLIER_NAME", "SUPPLIER_SHORT_NAME", "SUPPLIER_CLASS_ID", "SUPPLIER_CLASS_COLOUR", "SUPPLIER_PROFILE_1", "SUPPLIER_PROFILE_2", "SUPPLIER_WEBSITE", "SUPPLIER_LOGO_LARGE", "SUPPLIER_LOGO_SMALL", "SUPPLIER_IMAGE_1", "SUPPLIER_IMAGE_2", "SUPPLIER_IMAGE_3", "SUPPLIER_IMAGE_4", "SUPPLIER_IMAGE_BACKGROUND", "SUPPLIER_LOGO_LARGE_SCALE_SMALLER", "PRODUCT_TYPE_ID", "PRODUCT_TYPE_NAME", "PRODUCT_ID", "PRODUCT_NAME", "PRODUCT_NAME_WEB", "PRODUCT_SHORT_NAME", "PRODUCT_SIPPLIER_ORDER", "PRODUCT_CLASS_COLOUR", "PRODUCT_ABOUT_1", "PRODUCT_ABOUT_2", "PRODUCT_LINK", "PRODUCT_ENQUIRE", "PRODUCT_IMAGE_LARGE", "PRODUCT_IMAGE_SMALL", "PRODUCT_IMAGE_1", "PRODUCT_IMAGE_2", "PRODUCT_IMAGE_3", "PRODUCT_IMAGE_4", "PRODUCT_ANCHOR_ID", "PRODUCT_IMAGE_LARGE_WIDTH", "PRODUCT_IMAGE_LARGE_HEIGHT", "PRODUCT_IMAGE_SMALL_WIDTH", "PRODUCT_IMAGE_SMALL_HEIGHT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
  p.BUSINESS                                AS PRODUCT_BUSINESS,
  p.PRODUCT_TYPE                            AS PRODUCT_TYPE,
  d.DISCIPLINE_NAME                         AS DISCIPLINE,
  d.DISCIPLINE_ID                           AS DISCIPLINE_ID,
  pg.PRODUCT_GROUP_NAME                     AS PRODUCT_GROUP,
  p.PRODUCT_GROUP_ID                        AS PRODUCT_GROUP_ID,
  p.PRODUCT_GROUP_TYPE_ALT_ID               AS PRODUCT_GROUP_TYPE_ALT_ID,
  pga.PRODUCT_GROUP_NAME                    AS PRODUCT_GROUP_TYPE_ALT,
  s.SUPPLIER_ID                             AS SUPPLIER_ID,
  s.SUPPLIER_NAME                           AS SUPPLIER_NAME,
  s.SHORT_NAME                              AS SUPPLIER_SHORT_NAME,
  s.CLASS_ID                                AS SUPPLIER_CLASS_ID,
  s.CLASS_COLOUR                            AS SUPPLIER_CLASS_COLOUR,
  s.PROFILE_1                               AS SUPPLIER_PROFILE_1,
  s.PROFILE_2                               AS SUPPLIER_PROFILE_2,
  s.WEBSITE                                 AS SUPPLIER_WEBSITE,
  PRODUCT_IMAGE_DISPLAY(ws.RUNTIME_WORKSPACE, 'assets/images/Scientific/suppliers/', s.SUPPLIER_LOGO_LARGE, 'N')       AS SUPPLIER_LOGO_LARGE,
  PRODUCT_IMAGE_DISPLAY(ws.RUNTIME_WORKSPACE, 'assets/images/Scientific/suppliers/', s.SUPPLIER_LOGO_SMALL, 'N')       AS SUPPLIER_LOGO_SMALL,
  PRODUCT_IMAGE_DISPLAY(ws.RUNTIME_WORKSPACE, 'assets/images/Scientific/suppliers/', s.SUPPLIER_IMAGE_1, 'N')          AS SUPPLIER_IMAGE_1,
  PRODUCT_IMAGE_DISPLAY(ws.RUNTIME_WORKSPACE, 'assets/images/Scientific/suppliers/', s.SUPPLIER_IMAGE_2, 'N')          AS SUPPLIER_IMAGE_2,
  PRODUCT_IMAGE_DISPLAY(ws.RUNTIME_WORKSPACE, 'assets/images/Scientific/suppliers/', s.SUPPLIER_IMAGE_3, 'N')          AS SUPPLIER_IMAGE_3,
  PRODUCT_IMAGE_DISPLAY(ws.RUNTIME_WORKSPACE, 'assets/images/Scientific/suppliers/', s.SUPPLIER_IMAGE_4, 'N')          AS SUPPLIER_IMAGE_4,
  PRODUCT_IMAGE_DISPLAY(ws.RUNTIME_WORKSPACE, 'assets/images/Scientific/suppliers/', s.SUPPLIER_IMAGE_BACKGROUND, 'N') AS SUPPLIER_IMAGE_BACKGROUND,
  s.SUPPLIER_LOGO_LARGE_SCALE_SMALLER       AS SUPPLIER_LOGO_LARGE_SCALE_SMALLER,
  t.PRODUCT_TYPE_ID                         AS PRODUCT_TYPE_ID,
  t.PRODUCT_TYPE_NAME                       AS PRODUCT_TYPE_NAME,
  p.PRODUCT_ID                              AS PRODUCT_ID,
  p.PRODUCT_NAME                            AS PRODUCT_NAME,
  p.PRODUCT_NAME_WEB                        AS PRODUCT_NAME_WEB,
  p.SHORT_NAME                              AS PRODUCT_SHORT_NAME,
  p.PRODUCT_SIPPLIER_ORDER                  AS PRODUCT_SIPPLIER_ORDER,
  p.CLASS_COLOUR                            AS PRODUCT_CLASS_COLOUR,
  p.ABOUT_1                                 AS PRODUCT_ABOUT_1,
  p.ABOUT_2                                 AS PRODUCT_ABOUT_2,
  p.PRODUCT_LINK                            AS PRODUCT_LINK,
  p.PRODUCT_ENQUIRE                         AS PRODUCT_ENQUIRE,
  PRODUCT_IMAGE_DISPLAY(ws.RUNTIME_WORKSPACE, 'assets/images/Scientific/suppliers/', p.PRODUCT_IMAGE_LARGE, p.PRODUCT_IMAGE_EXTERNAL) AS PRODUCT_IMAGE_LARGE,
  PRODUCT_IMAGE_DISPLAY(ws.RUNTIME_WORKSPACE, 'assets/images/Scientific/suppliers/', p.PRODUCT_IMAGE_SMALL, p.PRODUCT_IMAGE_EXTERNAL) AS PRODUCT_IMAGE_SMALL,
  PRODUCT_IMAGE_DISPLAY(ws.RUNTIME_WORKSPACE, 'assets/images/Scientific/suppliers/', p.PRODUCT_IMAGE_1, p.PRODUCT_IMAGE_EXTERNAL)     AS PRODUCT_IMAGE_1,
  PRODUCT_IMAGE_DISPLAY(ws.RUNTIME_WORKSPACE, 'assets/images/Scientific/suppliers/', p.PRODUCT_IMAGE_2, p.PRODUCT_IMAGE_EXTERNAL)     AS PRODUCT_IMAGE_2,
  PRODUCT_IMAGE_DISPLAY(ws.RUNTIME_WORKSPACE, 'assets/images/Scientific/suppliers/', p.PRODUCT_IMAGE_3, p.PRODUCT_IMAGE_EXTERNAL)     AS PRODUCT_IMAGE_3,
  PRODUCT_IMAGE_DISPLAY(ws.RUNTIME_WORKSPACE, 'assets/images/Scientific/suppliers/', p.PRODUCT_IMAGE_4, p.PRODUCT_IMAGE_EXTERNAL)     AS PRODUCT_IMAGE_4,
  p.ANCHOR_ID                               AS PRODUCT_ANCHOR_ID,
  p.PRODUCT_IMAGE_LARGE_WIDTH               AS PRODUCT_IMAGE_LARGE_WIDTH,
  p.PRODUCT_IMAGE_LARGE_HEIGHT              AS PRODUCT_IMAGE_LARGE_HEIGHT,
  p.PRODUCT_IMAGE_SMALL_WIDTH               AS PRODUCT_IMAGE_SMALL_WIDTH,
  p.PRODUCT_IMAGE_SMALL_HEIGHT              AS PRODUCT_IMAGE_SMALL_HEIGHT
FROM SUPPLIERS s,
     PRODUCTS p,
     PRODUCT_TYPE t,
     PRODUCT_GROUP pg,
     PRODUCT_GROUP pga,
     DISCIPLINE d,
     (
       SELECT NVL(NULLIF(SYS_CONTEXT('APEX$SESSION', 'WORKSPACE'), ''), 'SYNTEC') AS RUNTIME_WORKSPACE
       FROM dual
     ) ws
WHERE p.SUPPLIER_ID = s.SUPPLIER_ID
  AND s.DELETED = 'N'
  AND s.ACTIVE = 'Y'
  AND p.PRODUCT_GROUP_ID = pg.PRODUCT_GROUP_ID
  AND p.PRODUCT_GROUP_TYPE_ALT_ID = pga.PRODUCT_GROUP_ID(+)
  AND p.PRODUCT_TYPE_ID = t.PRODUCT_TYPE_ID
  AND p.DELETED = 'N'
  AND p.ACTIVE = 'Y'
  AND pg.DELETED = 'N'
  AND pg.ACTIVE = 'Y'
  AND d.DISCIPLINE_ID = p.DISCIPLINE_ID
;
