--------------------------------------------------------
--  Constraints for Table PRODUCT_GROUP
--------------------------------------------------------

  ALTER TABLE "WEB"."PRODUCT_GROUP" MODIFY ("PRODUCT_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_GROUP" MODIFY ("PRODUCT_GROUP_NAME" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_GROUP" ADD CHECK (deleted IN ('Y', 'N')) ENABLE;
  ALTER TABLE "WEB"."PRODUCT_GROUP" ADD CHECK (active IN ('Y', 'N')) ENABLE;
  ALTER TABLE "WEB"."PRODUCT_GROUP" ADD CONSTRAINT "PK_PRODUCT_GROUP" PRIMARY KEY ("PRODUCT_GROUP_ID")
  USING INDEX "WEB"."PK_PRODUCT_GROUP"  ENABLE;
