--------------------------------------------------------
--  Constraints for Table PRODUCT_FACET_VALUE
--------------------------------------------------------

  ALTER TABLE "WEB"."PRODUCT_FACET_VALUE" MODIFY ("PRODUCT_FACET_VALUE_ID" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_FACET_VALUE" MODIFY ("CANONICAL_PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_FACET_VALUE" MODIFY ("FACET_ID" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_FACET_VALUE" MODIFY ("FACET_VALUE" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_FACET_VALUE" MODIFY ("ACTIVE_YN" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_FACET_VALUE" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_FACET_VALUE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_FACET_VALUE" ADD CONSTRAINT "CK_PROD_FACET_ACTIVE" CHECK (ACTIVE_YN in ('Y','N')) ENABLE;
  ALTER TABLE "WEB"."PRODUCT_FACET_VALUE" ADD PRIMARY KEY ("PRODUCT_FACET_VALUE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "WEB"."PRODUCT_FACET_VALUE" ADD CONSTRAINT "UQ_PROD_FACET" UNIQUE ("CANONICAL_PRODUCT_ID", "FACET_ID", "FACET_VALUE_NORM")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 158 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
