--------------------------------------------------------
--  DDL for Table PRODUCTS_VAZYME
--------------------------------------------------------

  CREATE TABLE "WEB"."PRODUCTS_VAZYME" 
   (	"PRODUCT_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SKU" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORY_OTHER" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ABOUT_1" CLOB COLLATE "USING_NLS_COMP", 
	"ABOUT_2" CLOB COLLATE "USING_NLS_COMP", 
	"PRODUCT_LINK" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_IMAGE_LINK" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"DISCIPLINE_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_GROUP_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DISCIPLINE_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_GROUP_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 LOB ("ABOUT_1") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("ABOUT_2") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
