REM INSERTING into WEB.PRODUCT_TYPE
SET DEFINE OFF;
Insert into WEB.PRODUCT_TYPE (DELETED,ACTIVE,PRODUCT_TYPE_ID,PRODUCT_TYPE_NAME,PRODUCT_TYPE_ICON_CLASS,PRODUCT_TYPE_ORDER,DATE_CREATED,DATE_DELETED,ANCHOR_ID) values ('N','Y','PTY-0004','Accessories',null,20,to_date('26-MAR-25','DD-MON-RR'),null,null);
Insert into WEB.PRODUCT_TYPE (DELETED,ACTIVE,PRODUCT_TYPE_ID,PRODUCT_TYPE_NAME,PRODUCT_TYPE_ICON_CLASS,PRODUCT_TYPE_ORDER,DATE_CREATED,DATE_DELETED,ANCHOR_ID) values ('N','Y','PTY-0005','Related Products',null,6,to_date('26-MAR-25','DD-MON-RR'),null,null);
Insert into WEB.PRODUCT_TYPE (DELETED,ACTIVE,PRODUCT_TYPE_ID,PRODUCT_TYPE_NAME,PRODUCT_TYPE_ICON_CLASS,PRODUCT_TYPE_ORDER,DATE_CREATED,DATE_DELETED,ANCHOR_ID) values ('N','Y','PTY-0001','Diagnostic Systems',null,1,to_date('21-JAN-25','DD-MON-RR'),null,null);
Insert into WEB.PRODUCT_TYPE (DELETED,ACTIVE,PRODUCT_TYPE_ID,PRODUCT_TYPE_NAME,PRODUCT_TYPE_ICON_CLASS,PRODUCT_TYPE_ORDER,DATE_CREATED,DATE_DELETED,ANCHOR_ID) values ('N','Y','PTY-0002','Consumables',null,5,to_date('21-JAN-25','DD-MON-RR'),null,null);
Insert into WEB.PRODUCT_TYPE (DELETED,ACTIVE,PRODUCT_TYPE_ID,PRODUCT_TYPE_NAME,PRODUCT_TYPE_ICON_CLASS,PRODUCT_TYPE_ORDER,DATE_CREATED,DATE_DELETED,ANCHOR_ID) values ('N','Y','PTY-0003','Reagents',null,10,to_date('21-JAN-25','DD-MON-RR'),null,null);
