--------------------------------------------------------
--  Constraints for Table PRODUCT_TYPE
--------------------------------------------------------

  ALTER TABLE "WEB"."PRODUCT_TYPE" MODIFY ("PRODUCT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_TYPE" MODIFY ("PRODUCT_TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "WEB"."PRODUCT_TYPE" ADD CHECK (deleted IN ('Y', 'N')) ENABLE;
  ALTER TABLE "WEB"."PRODUCT_TYPE" ADD CHECK (active IN ('Y', 'N')) ENABLE;
  ALTER TABLE "WEB"."PRODUCT_TYPE" ADD CONSTRAINT "PK_PRODUCT_TYPE" PRIMARY KEY ("PRODUCT_TYPE_ID")
  USING INDEX "WEB"."PK_PRODUCT_TYPE"  ENABLE;
