--------------------------------------------------------
--  DDL for Table SUPPLIERS_STAGING
--------------------------------------------------------

  CREATE TABLE "WEB"."SUPPLIERS_STAGING" 
   (	"DELETED" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SHORT_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CLASS_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CLASS_COLOUR" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PROFILE_1" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PROFILE_2" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"BUSINESS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"WEBSITE" VARCHAR2(800 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_LOGO_LARGE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_LOGO_SMALL" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_IMAGE_1" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_IMAGE_2" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_IMAGE_3" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_IMAGE_4" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_1" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_2" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_3" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_4" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_5" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DATE_CREATED" DATE, 
	"DATE_DELETED" DATE, 
	"ANCHOR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_IMAGE_BACKGROUND" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_LOGO_LARGE_SCALE_SMALLER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
