REM INSERTING into WEB.SYNTEC_JOB_TITLES
SET DEFINE OFF;
Insert into WEB.SYNTEC_JOB_TITLES (JOB_TITLE_ID,JOB_TITLE_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (12,'Founder & CEO','Y','N',10);
Insert into WEB.SYNTEC_JOB_TITLES (JOB_TITLE_ID,JOB_TITLE_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (13,'Sales Director','Y','N',20);
Insert into WEB.SYNTEC_JOB_TITLES (JOB_TITLE_ID,JOB_TITLE_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (14,'Business Development Executive','Y','N',30);
Insert into WEB.SYNTEC_JOB_TITLES (JOB_TITLE_ID,JOB_TITLE_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (15,'Product Sales Specialist','Y','N',40);
Insert into WEB.SYNTEC_JOB_TITLES (JOB_TITLE_ID,JOB_TITLE_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (16,'Key Account Manager','Y','N',50);
Insert into WEB.SYNTEC_JOB_TITLES (JOB_TITLE_ID,JOB_TITLE_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (17,'General Operations Manager','Y','N',60);
Insert into WEB.SYNTEC_JOB_TITLES (JOB_TITLE_ID,JOB_TITLE_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (18,'Logistics Manager','Y','N',70);
Insert into WEB.SYNTEC_JOB_TITLES (JOB_TITLE_ID,JOB_TITLE_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (19,'Warehouse Logistics Operator','Y','N',80);
Insert into WEB.SYNTEC_JOB_TITLES (JOB_TITLE_ID,JOB_TITLE_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (20,'Service Engineer','Y','N',90);
Insert into WEB.SYNTEC_JOB_TITLES (JOB_TITLE_ID,JOB_TITLE_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (21,'Accounts Manager','Y','N',100);
Insert into WEB.SYNTEC_JOB_TITLES (JOB_TITLE_ID,JOB_TITLE_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (22,'Chief Scientific Officer','Y','N',110);
Insert into WEB.SYNTEC_JOB_TITLES (JOB_TITLE_ID,JOB_TITLE_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (30,'IT Support','Y','N',120);
