REM INSERTING into WEB.SYNTEC_MESSAGE_ENQUIRY_TYPE
SET DEFINE OFF;
Insert into WEB.SYNTEC_MESSAGE_ENQUIRY_TYPE (ENQUIRY_TYPE_ID,ENQUIRY_TYPE_DESCRIPTION,EMAIL_ADDRESS,ACTIVE,DELETED) values (1,'Sales','syntec.website@gmail.com','Y','N');
Insert into WEB.SYNTEC_MESSAGE_ENQUIRY_TYPE (ENQUIRY_TYPE_ID,ENQUIRY_TYPE_DESCRIPTION,EMAIL_ADDRESS,ACTIVE,DELETED) values (2,'Support','syntec.website@gmail.com','Y','N');
Insert into WEB.SYNTEC_MESSAGE_ENQUIRY_TYPE (ENQUIRY_TYPE_ID,ENQUIRY_TYPE_DESCRIPTION,EMAIL_ADDRESS,ACTIVE,DELETED) values (3,'Accounts','syntec.website@gmail.com','Y','N');
Insert into WEB.SYNTEC_MESSAGE_ENQUIRY_TYPE (ENQUIRY_TYPE_ID,ENQUIRY_TYPE_DESCRIPTION,EMAIL_ADDRESS,ACTIVE,DELETED) values (4,'Service','syntec.website@gmail.com','Y','N');
Insert into WEB.SYNTEC_MESSAGE_ENQUIRY_TYPE (ENQUIRY_TYPE_ID,ENQUIRY_TYPE_DESCRIPTION,EMAIL_ADDRESS,ACTIVE,DELETED) values (30,'General Enquiry','syntec.website@gmail.com','Y','N');
Insert into WEB.SYNTEC_MESSAGE_ENQUIRY_TYPE (ENQUIRY_TYPE_ID,ENQUIRY_TYPE_DESCRIPTION,EMAIL_ADDRESS,ACTIVE,DELETED) values (5,'Distribution','syntec.website@gmail.com','Y','N');
