--------------------------------------------------------
--  Constraints for Table SYNTEC_USERS
--------------------------------------------------------

  ALTER TABLE "WEB"."SYNTEC_USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "WEB"."SYNTEC_USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
