--------------------------------------------------------
--  DDL for Sequence SYNTEC_WEBSITE_MESSAGE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WEB"."SYNTEC_WEBSITE_MESSAGE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 601 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
