REM INSERTING into WEB.SYNTEC_DIVISIONS
SET DEFINE OFF;
Insert into WEB.SYNTEC_DIVISIONS (DIVISION_ID,DIVISION_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (6,'Sales','Y','N',10);
Insert into WEB.SYNTEC_DIVISIONS (DIVISION_ID,DIVISION_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (7,'Logistics','Y','N',20);
Insert into WEB.SYNTEC_DIVISIONS (DIVISION_ID,DIVISION_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (8,'Service','Y','N',30);
Insert into WEB.SYNTEC_DIVISIONS (DIVISION_ID,DIVISION_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (9,'Accounts','Y','N',40);
Insert into WEB.SYNTEC_DIVISIONS (DIVISION_ID,DIVISION_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (10,'Laboratory','Y','N',50);
Insert into WEB.SYNTEC_DIVISIONS (DIVISION_ID,DIVISION_DESCRIPTION,ACTIVE,DELETED,SORT_ORDER) values (20,'Technology','Y','N',60);
