REM INSERTING into WEB.SYNTEC_SOURCES
SET DEFINE OFF;
Insert into WEB.SYNTEC_SOURCES (SOURCE_TYPE_ID,SOURCE_DESCRIPTION) values (1,'Products');
Insert into WEB.SYNTEC_SOURCES (SOURCE_TYPE_ID,SOURCE_DESCRIPTION) values (2,'Contact Us Form');
Insert into WEB.SYNTEC_SOURCES (SOURCE_TYPE_ID,SOURCE_DESCRIPTION) values (3,'Contact Us Team');
Insert into WEB.SYNTEC_SOURCES (SOURCE_TYPE_ID,SOURCE_DESCRIPTION) values (4,'Contact Us Team Sales, Support & Servicing
');
