REM INSERTING into WEB.SYNTEC_CONFIG
SET DEFINE OFF;
Insert into WEB.SYNTEC_CONFIG (CONFIG_KEY,CONFIG_VALUE) values ('STATIC_FILE_BASE_URL','https://www.syntec.ie/ords/');
Insert into WEB.SYNTEC_CONFIG (CONFIG_KEY,CONFIG_VALUE) values ('STATIC_ALIAS_DEV','syntec_dev');
Insert into WEB.SYNTEC_CONFIG (CONFIG_KEY,CONFIG_VALUE) values ('STATIC_ALIAS_PROD','syntec');
Insert into WEB.SYNTEC_CONFIG (CONFIG_KEY,CONFIG_VALUE) values ('STATIC_VERSION_DEV','v3931');
Insert into WEB.SYNTEC_CONFIG (CONFIG_KEY,CONFIG_VALUE) values ('STATIC_VERSION_PROD','v3211');
