--------------------------------------------------------
--  Constraints for Table SYNTEC_MESSAGE_ENQUIRY_TYPE
--------------------------------------------------------

  ALTER TABLE "WEB"."SYNTEC_MESSAGE_ENQUIRY_TYPE" MODIFY ("ENQUIRY_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "WEB"."SYNTEC_MESSAGE_ENQUIRY_TYPE" MODIFY ("ENQUIRY_TYPE_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "WEB"."SYNTEC_MESSAGE_ENQUIRY_TYPE" ADD CHECK (active IN ('Y', 'N')) ENABLE;
  ALTER TABLE "WEB"."SYNTEC_MESSAGE_ENQUIRY_TYPE" ADD CHECK (deleted IN ('Y', 'N')) ENABLE;
  ALTER TABLE "WEB"."SYNTEC_MESSAGE_ENQUIRY_TYPE" ADD PRIMARY KEY ("ENQUIRY_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
