--------------------------------------------------------
--  DDL for Index UQ_PROD_FACET
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEB"."UQ_PROD_FACET" ON "WEB"."PRODUCT_FACET_VALUE" ("CANONICAL_PRODUCT_ID", "FACET_ID", "FACET_VALUE_NORM") 
  PCTFREE 10 INITRANS 20 MAXTRANS 158 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
