--------------------------------------------------------
--  DDL for Index UX_PRODUCTS_SUPP_SUPP_PROD_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEB"."UX_PRODUCTS_SUPP_SUPP_PROD_ID" ON "WEB"."PRODUCTS" ("SUPPLIER_ID", CASE  WHEN "SUPPLIER_PRODUCT_ID" IS NULL THEN "PRODUCT_ID" ELSE "SUPPLIER_PRODUCT_ID" END ) 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
