--------------------------------------------------------
--  DDL for View VW_ANTIBODY_APPLICATION_CATEGORIES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WEB"."VW_ANTIBODY_APPLICATION_CATEGORIES" ("ID", "CATEGORY") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    A.ID,
    TRIM(REGEXP_SUBSTR(A.APPLICATION_CATEGORIES, '[^|]+', 1, LEVEL)) AS CATEGORY
FROM ANTIBODIES A
CONNECT BY REGEXP_SUBSTR(A.APPLICATION_CATEGORIES, '[^|]+', 1, LEVEL) IS NOT NULL
AND PRIOR A.ID = A.ID
AND PRIOR DBMS_RANDOM.VALUE IS NOT NULL
;
