CREATE TABLE IF NOT EXISTS syntec_suppliers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  supplier_id VARCHAR(20) NULL,
  supplier_name VARCHAR(255) NOT NULL,
  short_name VARCHAR(255) NULL,
  class_id VARCHAR(100) NULL,
  class_colour VARCHAR(20) NULL,
  profile_1 LONGTEXT NULL,
  profile_2 LONGTEXT NULL,
  business VARCHAR(255) NULL,
  website VARCHAR(1024) NULL,
  supplier_logo_large VARCHAR(255) NULL,
  supplier_logo_small VARCHAR(255) NULL,
  supplier_image_1 VARCHAR(255) NULL,
  supplier_image_2 VARCHAR(255) NULL,
  supplier_image_3 VARCHAR(255) NULL,
  supplier_image_4 VARCHAR(255) NULL,
  address_1 VARCHAR(255) NULL,
  address_2 VARCHAR(255) NULL,
  address_3 VARCHAR(255) NULL,
  address_4 VARCHAR(255) NULL,
  address_5 VARCHAR(255) NULL,
  date_created DATETIME NULL,
  date_deleted DATETIME NULL,
  anchor_id VARCHAR(255) NULL,
  supplier_image_background VARCHAR(255) NULL,
  supplier_logo_large_scale_smaller VARCHAR(100) NULL,
  slug VARCHAR(255) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  active_flag TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_syntec_suppliers_slug (slug),
  KEY idx_syntec_suppliers_active_sort (active_flag, sort_order),
  KEY idx_syntec_suppliers_name (supplier_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
