-- Oracle SUPPLIERS direct migration to syntec_suppliers
-- Uses a full Oracle-shaped staging table, then upserts runtime fields.

CREATE TABLE IF NOT EXISTS syntec_suppliers_staging (
  deleted CHAR(1) NULL,
  active CHAR(1) NULL,
  supplier_id VARCHAR(20) NOT NULL,
  supplier_name VARCHAR(255) NOT NULL,
  short_name VARCHAR(255) NULL,
  class_id VARCHAR(100) NULL,
  class_colour VARCHAR(20) NULL,
  profile_1 LONGTEXT NULL,
  profile_2 LONGTEXT NULL,
  business VARCHAR(255) NULL,
  website VARCHAR(1024) NULL,
  supplier_logo_large VARCHAR(255) NULL,
  supplier_logo_small VARCHAR(255) NULL,
  supplier_image_1 VARCHAR(255) NULL,
  supplier_image_2 VARCHAR(255) NULL,
  supplier_image_3 VARCHAR(255) NULL,
  supplier_image_4 VARCHAR(255) NULL,
  address_1 VARCHAR(255) NULL,
  address_2 VARCHAR(255) NULL,
  address_3 VARCHAR(255) NULL,
  address_4 VARCHAR(255) NULL,
  address_5 VARCHAR(255) NULL,
  date_created DATETIME NULL,
  date_deleted DATETIME NULL,
  anchor_id VARCHAR(255) NULL,
  supplier_image_background VARCHAR(255) NULL,
  supplier_logo_large_scale_smaller VARCHAR(100) NULL,
  PRIMARY KEY (supplier_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO syntec_suppliers (
  supplier_id,
  supplier_name,
  short_name,
  class_id,
  class_colour,
  profile_1,
  profile_2,
  business,
  website,
  supplier_logo_large,
  supplier_logo_small,
  supplier_image_1,
  supplier_image_2,
  supplier_image_3,
  supplier_image_4,
  address_1,
  address_2,
  address_3,
  address_4,
  address_5,
  date_created,
  date_deleted,
  anchor_id,
  supplier_image_background,
  supplier_logo_large_scale_smaller,
  slug,
  sort_order,
  active_flag,
  created_at,
  updated_at
)
SELECT
  s.supplier_id,
  s.supplier_name,
  s.short_name,
  s.class_id,
  s.class_colour,
  s.profile_1,
  s.profile_2,
  s.business,
  s.website,
  s.supplier_logo_large,
  s.supplier_logo_small,
  s.supplier_image_1,
  s.supplier_image_2,
  s.supplier_image_3,
  s.supplier_image_4,
  s.address_1,
  s.address_2,
  s.address_3,
  s.address_4,
  s.address_5,
  s.date_created,
  s.date_deleted,
  s.anchor_id,
  s.supplier_image_background,
  s.supplier_logo_large_scale_smaller,
  COALESCE(NULLIF(TRIM(s.anchor_id), ''), LOWER(REPLACE(REPLACE(REPLACE(TRIM(s.supplier_name), ' ', '-'), '/', '-'), '&', 'and'))) AS slug,
  0,
  CASE WHEN COALESCE(s.active, 'Y') = 'Y' THEN 1 ELSE 0 END,
  COALESCE(s.date_created, NOW()),
  NOW()
FROM syntec_suppliers_staging s
ON DUPLICATE KEY UPDATE
  supplier_name = VALUES(supplier_name),
  short_name = VALUES(short_name),
  class_id = VALUES(class_id),
  class_colour = VALUES(class_colour),
  profile_1 = VALUES(profile_1),
  profile_2 = VALUES(profile_2),
  business = VALUES(business),
  website = VALUES(website),
  supplier_logo_large = VALUES(supplier_logo_large),
  supplier_logo_small = VALUES(supplier_logo_small),
  supplier_image_1 = VALUES(supplier_image_1),
  supplier_image_2 = VALUES(supplier_image_2),
  supplier_image_3 = VALUES(supplier_image_3),
  supplier_image_4 = VALUES(supplier_image_4),
  address_1 = VALUES(address_1),
  address_2 = VALUES(address_2),
  address_3 = VALUES(address_3),
  address_4 = VALUES(address_4),
  address_5 = VALUES(address_5),
  date_created = VALUES(date_created),
  date_deleted = VALUES(date_deleted),
  anchor_id = VALUES(anchor_id),
  supplier_image_background = VALUES(supplier_image_background),
  supplier_logo_large_scale_smaller = VALUES(supplier_logo_large_scale_smaller),
  slug = VALUES(slug),
  sort_order = VALUES(sort_order),
  active_flag = VALUES(active_flag),
  updated_at = NOW();

SELECT COUNT(*) AS staged_rows FROM syntec_suppliers_staging;
SELECT COUNT(*) AS runtime_rows FROM syntec_suppliers;
SELECT COUNT(*) AS missing_supplier_id
FROM syntec_suppliers
WHERE supplier_id IS NULL OR supplier_id = '';
