CREATE TABLE IF NOT EXISTS syntec_products (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id VARCHAR(20) NULL,
  product_name VARCHAR(255) NOT NULL,
  product_name_web VARCHAR(255) NULL,
  short_name VARCHAR(255) NULL,
  product_sipplier_order BIGINT NULL,
  supplier_id VARCHAR(20) NULL,
  discipline VARCHAR(255) NULL,
  product_group VARCHAR(255) NULL,
  product_type VARCHAR(255) NULL,
  class_id VARCHAR(255) NULL,
  class_colour VARCHAR(64) NULL,
  about_1 LONGTEXT NULL,
  about_2 LONGTEXT NULL,
  product_link VARCHAR(1024) NULL,
  product_enquire VARCHAR(1024) NULL,
  product_image_large VARCHAR(255) NULL,
  product_image_small VARCHAR(255) NULL,
  product_image_1 VARCHAR(255) NULL,
  product_image_2 VARCHAR(255) NULL,
  product_image_3 VARCHAR(255) NULL,
  product_image_4 VARCHAR(255) NULL,
  product_parent_id VARCHAR(20) NULL,
  date_created DATETIME NULL,
  date_deleted DATETIME NULL,
  anchor_id VARCHAR(255) NULL,
  product_image_large_width VARCHAR(32) NULL,
  product_image_large_height VARCHAR(32) NULL,
  product_image_small_width VARCHAR(32) NULL,
  product_image_small_height VARCHAR(32) NULL,
  supplier_name VARCHAR(255) NULL,
  discipline_id VARCHAR(20) NULL,
  product_group_id VARCHAR(20) NULL,
  product_type_id VARCHAR(20) NULL,
  product_group_type_alt VARCHAR(255) NULL,
  product_group_type_alt_id VARCHAR(20) NULL,
  business VARCHAR(255) NULL,
  product_image_external VARCHAR(1) NULL,
  prouduct_sku VARCHAR(100) NULL,
  supplier_product_id VARCHAR(255) NULL,
  slug VARCHAR(255) NOT NULL,
  active_flag TINYINT(1) NOT NULL DEFAULT 1,
  featured_flag TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_syntec_products_slug (slug),
  KEY idx_syntec_products_supplier_id (supplier_id),
  KEY idx_syntec_products_product_name (product_name),
  KEY idx_syntec_products_active_sort (active_flag, product_sipplier_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
