-- Oracle PRODUCTS direct migration to syntec_products (with full Oracle-shaped staging)

CREATE TABLE IF NOT EXISTS syntec_products_staging (
  deleted CHAR(1) NULL,
  active CHAR(1) NULL,
  product_id VARCHAR(20) NOT NULL,
  product_name VARCHAR(255) NOT NULL,
  product_name_web VARCHAR(255) NULL,
  short_name VARCHAR(255) NULL,
  product_sipplier_order BIGINT NULL,
  supplier_id VARCHAR(20) NULL,
  discipline VARCHAR(255) NULL,
  product_group VARCHAR(255) NULL,
  product_type VARCHAR(255) NULL,
  class_id VARCHAR(255) NULL,
  class_colour VARCHAR(64) NULL,
  about_1 LONGTEXT NULL,
  about_2 LONGTEXT NULL,
  product_link VARCHAR(1024) NULL,
  product_enquire VARCHAR(1024) NULL,
  product_image_large VARCHAR(255) NULL,
  product_image_small VARCHAR(255) NULL,
  product_image_1 VARCHAR(255) NULL,
  product_image_2 VARCHAR(255) NULL,
  product_image_3 VARCHAR(255) NULL,
  product_image_4 VARCHAR(255) NULL,
  product_parent_id VARCHAR(20) NULL,
  date_created DATETIME NULL,
  date_deleted DATETIME NULL,
  anchor_id VARCHAR(255) NULL,
  product_image_large_width VARCHAR(32) NULL,
  product_image_large_height VARCHAR(32) NULL,
  product_image_small_width VARCHAR(32) NULL,
  product_image_small_height VARCHAR(32) NULL,
  supplier_name VARCHAR(255) NULL,
  discipline_id VARCHAR(20) NULL,
  product_group_id VARCHAR(20) NULL,
  product_type_id VARCHAR(20) NULL,
  product_group_type_alt VARCHAR(255) NULL,
  product_group_type_alt_id VARCHAR(20) NULL,
  business VARCHAR(255) NULL,
  product_image_external VARCHAR(1) NULL,
  prouduct_sku VARCHAR(100) NULL,
  supplier_product_id VARCHAR(255) NULL,
  PRIMARY KEY (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO syntec_products (
  product_id,
  product_name,
  product_name_web,
  short_name,
  product_sipplier_order,
  supplier_id,
  discipline,
  product_group,
  product_type,
  class_id,
  class_colour,
  about_1,
  about_2,
  product_link,
  product_enquire,
  product_image_large,
  product_image_small,
  product_image_1,
  product_image_2,
  product_image_3,
  product_image_4,
  product_parent_id,
  date_created,
  date_deleted,
  anchor_id,
  product_image_large_width,
  product_image_large_height,
  product_image_small_width,
  product_image_small_height,
  supplier_name,
  discipline_id,
  product_group_id,
  product_type_id,
  product_group_type_alt,
  product_group_type_alt_id,
  business,
  product_image_external,
  prouduct_sku,
  supplier_product_id,
  slug,
  active_flag,
  featured_flag,
  created_at,
  updated_at
)
SELECT
  s.product_id,
  TRIM(REPLACE(REPLACE(REPLACE(COALESCE(s.product_name, ''), '�', ''), '', ''''), '–', '-')),
  s.product_name_web,
  s.short_name,
  s.product_sipplier_order,
  s.supplier_id,
  s.discipline,
  s.product_group,
  s.product_type,
  s.class_id,
  s.class_colour,
  s.about_1,
  s.about_2,
  s.product_link,
  s.product_enquire,
  s.product_image_large,
  s.product_image_small,
  s.product_image_1,
  s.product_image_2,
  s.product_image_3,
  s.product_image_4,
  s.product_parent_id,
  s.date_created,
  s.date_deleted,
  s.anchor_id,
  s.product_image_large_width,
  s.product_image_large_height,
  s.product_image_small_width,
  s.product_image_small_height,
  s.supplier_name,
  s.discipline_id,
  s.product_group_id,
  s.product_type_id,
  s.product_group_type_alt,
  s.product_group_type_alt_id,
  s.business,
  s.product_image_external,
  NULLIF(s.prouduct_sku, ''),
  s.supplier_product_id,
  CASE
    WHEN TRIM(COALESCE(s.anchor_id, '')) <> '' THEN CONCAT(TRIM(REPLACE(REPLACE(REPLACE(COALESCE(s.anchor_id, ''), '�', ''), '', ''''), '–', '-')), '-', LOWER(REPLACE(s.product_id, 'PRD-', '')))
    ELSE CONCAT(LOWER(REPLACE(REPLACE(REPLACE(TRIM(REPLACE(REPLACE(REPLACE(COALESCE(s.product_name, ''), '�', ''), '', ''''), '–', '-')), ' ', '-'), '/', '-'), '&', 'and')), '-', LOWER(REPLACE(s.product_id, 'PRD-', '')))
  END,
  CASE WHEN COALESCE(s.active, 'Y') = 'Y' THEN 1 ELSE 0 END,
  0,
  COALESCE(s.date_created, NOW()),
  NOW()
FROM syntec_products_staging s
ON DUPLICATE KEY UPDATE
  product_name = VALUES(product_name),
  product_name_web = VALUES(product_name_web),
  short_name = VALUES(short_name),
  product_sipplier_order = VALUES(product_sipplier_order),
  supplier_id = VALUES(supplier_id),
  discipline = VALUES(discipline),
  product_group = VALUES(product_group),
  product_type = VALUES(product_type),
  class_id = VALUES(class_id),
  class_colour = VALUES(class_colour),
  about_1 = VALUES(about_1),
  about_2 = VALUES(about_2),
  product_link = VALUES(product_link),
  product_enquire = VALUES(product_enquire),
  product_image_large = VALUES(product_image_large),
  product_image_small = VALUES(product_image_small),
  product_image_1 = VALUES(product_image_1),
  product_image_2 = VALUES(product_image_2),
  product_image_3 = VALUES(product_image_3),
  product_image_4 = VALUES(product_image_4),
  product_parent_id = VALUES(product_parent_id),
  date_created = VALUES(date_created),
  date_deleted = VALUES(date_deleted),
  anchor_id = VALUES(anchor_id),
  product_image_large_width = VALUES(product_image_large_width),
  product_image_large_height = VALUES(product_image_large_height),
  product_image_small_width = VALUES(product_image_small_width),
  product_image_small_height = VALUES(product_image_small_height),
  supplier_name = VALUES(supplier_name),
  discipline_id = VALUES(discipline_id),
  product_group_id = VALUES(product_group_id),
  product_type_id = VALUES(product_type_id),
  product_group_type_alt = VALUES(product_group_type_alt),
  product_group_type_alt_id = VALUES(product_group_type_alt_id),
  business = VALUES(business),
  product_image_external = VALUES(product_image_external),
  prouduct_sku = VALUES(prouduct_sku),
  supplier_product_id = VALUES(supplier_product_id),
  slug = VALUES(slug),
  active_flag = VALUES(active_flag),
  updated_at = NOW();

SELECT COUNT(*) AS staged_rows FROM syntec_products_staging;
SELECT COUNT(*) AS runtime_rows FROM syntec_products;
SELECT COUNT(*) AS missing_supplier_id
FROM syntec_products
WHERE supplier_id IS NULL OR supplier_id = '';
