CREATE TABLE IF NOT EXISTS syntec_sources (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_type_code VARCHAR(20) NULL,
  name VARCHAR(255) NULL,
  slug VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_syntec_sources_slug (slug),
  KEY idx_syntec_sources_code (source_type_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
