CREATE TABLE IF NOT EXISTS syntec_users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_code VARCHAR(20) NULL,
  username VARCHAR(100) NULL,
  first_name VARCHAR(100) NULL,
  last_name VARCHAR(100) NULL,
  full_name VARCHAR(255) NULL,
  email VARCHAR(200) NULL,
  alt_email VARCHAR(200) NULL,
  phone_01 VARCHAR(50) NULL,
  phone_02 VARCHAR(50) NULL,
  mobile VARCHAR(50) NULL,
  job_title_code VARCHAR(20) NULL,
  division_code VARCHAR(20) NULL,
  user_role_code VARCHAR(20) NULL,
  access_level INT NULL,
  is_active CHAR(1) NOT NULL DEFAULT 'Y',
  is_deleted_yn CHAR(1) NOT NULL DEFAULT 'N',
  locked CHAR(1) NOT NULL DEFAULT 'N',
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_syntec_users_user_code (user_code),
  KEY idx_syntec_users_email (email),
  KEY idx_syntec_users_division_code (division_code),
  KEY idx_syntec_users_job_title_code (job_title_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
