-- phpMyAdmin-safe hybrid cleanup (no procedures, no delimiters)

/* helper pattern repeated:
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE ... DROP COLUMN ...','SELECT 1') FROM information_schema.columns ...);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
*/

/* syntec_discipline */
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_discipline DROP COLUMN id','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_discipline' AND column_name='id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_discipline DROP COLUMN name','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_discipline' AND column_name='name'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_discipline DROP COLUMN description','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_discipline' AND column_name='description'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_discipline DROP COLUMN discipline_code','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_discipline' AND column_name='discipline_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_discipline DROP COLUMN slug','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_discipline' AND column_name='slug'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_discipline DROP COLUMN sort_order','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_discipline' AND column_name='sort_order'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_discipline DROP COLUMN created_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_discipline' AND column_name='created_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_discipline DROP COLUMN updated_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_discipline' AND column_name='updated_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_discipline DROP COLUMN icon','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_discipline' AND column_name='icon'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_discipline DROP COLUMN image_path','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_discipline' AND column_name='image_path'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

/* syntec_product_group */
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_group DROP COLUMN id','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_group' AND column_name='id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_group DROP COLUMN name','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_group' AND column_name='name'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_group DROP COLUMN description','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_group' AND column_name='description'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_group DROP COLUMN product_group_code','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_group' AND column_name='product_group_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_group DROP COLUMN slug','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_group' AND column_name='slug'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_group DROP COLUMN sort_order','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_group' AND column_name='sort_order'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_group DROP COLUMN created_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_group' AND column_name='created_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_group DROP COLUMN updated_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_group' AND column_name='updated_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_group DROP COLUMN icon','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_group' AND column_name='icon'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_group DROP COLUMN image_path','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_group' AND column_name='image_path'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

/* syntec_product_type */
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_type DROP COLUMN id','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_type' AND column_name='id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_type DROP COLUMN name','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_type' AND column_name='name'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_type DROP COLUMN description','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_type' AND column_name='description'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_type DROP COLUMN product_type_code','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_type' AND column_name='product_type_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_type DROP COLUMN slug','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_type' AND column_name='slug'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_type DROP COLUMN sort_order','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_type' AND column_name='sort_order'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_type DROP COLUMN created_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_type' AND column_name='created_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_type DROP COLUMN updated_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_type' AND column_name='updated_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_type DROP COLUMN icon','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_type' AND column_name='icon'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_product_type DROP COLUMN image_path','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_product_type' AND column_name='image_path'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

/* syntec_divisions */
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_divisions DROP COLUMN id','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_divisions' AND column_name='id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_divisions DROP COLUMN name','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_divisions' AND column_name='name'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_divisions DROP COLUMN division_code','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_divisions' AND column_name='division_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_divisions DROP COLUMN sort_order','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_divisions' AND column_name='sort_order'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_divisions DROP COLUMN slug','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_divisions' AND column_name='slug'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_divisions DROP COLUMN created_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_divisions' AND column_name='created_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_divisions DROP COLUMN updated_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_divisions' AND column_name='updated_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_divisions DROP COLUMN active_flag','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_divisions' AND column_name='active_flag'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_divisions DROP COLUMN deleted_flag','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_divisions' AND column_name='deleted_flag'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

/* syntec_job_titles */
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_job_titles DROP COLUMN id','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_job_titles' AND column_name='id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_job_titles DROP COLUMN name','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_job_titles' AND column_name='name'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_job_titles DROP COLUMN job_title_code','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_job_titles' AND column_name='job_title_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_job_titles DROP COLUMN sort_order','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_job_titles' AND column_name='sort_order'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_job_titles DROP COLUMN slug','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_job_titles' AND column_name='slug'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_job_titles DROP COLUMN created_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_job_titles' AND column_name='created_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_job_titles DROP COLUMN updated_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_job_titles' AND column_name='updated_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_job_titles DROP COLUMN active_flag','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_job_titles' AND column_name='active_flag'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_job_titles DROP COLUMN deleted_flag','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_job_titles' AND column_name='deleted_flag'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

/* syntec_message_enquiry_type */
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_enquiry_type DROP COLUMN id','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_enquiry_type' AND column_name='id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_enquiry_type DROP COLUMN name','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_enquiry_type' AND column_name='name'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_enquiry_type DROP COLUMN enquiry_type_code','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_enquiry_type' AND column_name='enquiry_type_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_enquiry_type DROP COLUMN sort_order','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_enquiry_type' AND column_name='sort_order'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_enquiry_type DROP COLUMN slug','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_enquiry_type' AND column_name='slug'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_enquiry_type DROP COLUMN created_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_enquiry_type' AND column_name='created_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_enquiry_type DROP COLUMN updated_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_enquiry_type' AND column_name='updated_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_enquiry_type DROP COLUMN active_flag','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_enquiry_type' AND column_name='active_flag'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_enquiry_type DROP COLUMN deleted_flag','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_enquiry_type' AND column_name='deleted_flag'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

/* syntec_message_types */
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_types DROP COLUMN id','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_types' AND column_name='id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_types DROP COLUMN name','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_types' AND column_name='name'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_types DROP COLUMN message_type_code','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_types' AND column_name='message_type_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_types DROP COLUMN sort_order','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_types' AND column_name='sort_order'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_types DROP COLUMN slug','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_types' AND column_name='slug'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_types DROP COLUMN created_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_types' AND column_name='created_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_types DROP COLUMN updated_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_types' AND column_name='updated_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_types DROP COLUMN active_flag','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_types' AND column_name='active_flag'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_message_types DROP COLUMN deleted_flag','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_message_types' AND column_name='deleted_flag'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

/* syntec_sources */
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_sources DROP COLUMN id','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_sources' AND column_name='id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_sources DROP COLUMN name','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_sources' AND column_name='name'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_sources DROP COLUMN source_type_code','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_sources' AND column_name='source_type_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_sources DROP COLUMN sort_order','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_sources' AND column_name='sort_order'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_sources DROP COLUMN slug','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_sources' AND column_name='slug'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_sources DROP COLUMN created_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_sources' AND column_name='created_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_sources DROP COLUMN updated_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_sources' AND column_name='updated_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_sources DROP COLUMN active_flag','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_sources' AND column_name='active_flag'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_sources DROP COLUMN deleted_flag','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_sources' AND column_name='deleted_flag'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

/* syntec_users */
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_users DROP COLUMN id','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_users' AND column_name='id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_users DROP COLUMN user_code','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_users' AND column_name='user_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_users DROP COLUMN isactive','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_users' AND column_name='isactive'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_users DROP COLUMN active','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_users' AND column_name='active'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_users DROP COLUMN deleted','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_users' AND column_name='deleted'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_users DROP COLUMN slug','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_users' AND column_name='slug'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_users DROP COLUMN created_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_users' AND column_name='created_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_users DROP COLUMN updated_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_users' AND column_name='updated_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

/* syntec_messages */
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_messages DROP COLUMN id','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_messages' AND column_name='id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_messages DROP COLUMN message_code','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_messages' AND column_name='message_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_messages DROP COLUMN source_type_code','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_messages' AND column_name='source_type_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_messages DROP COLUMN message_type_code','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_messages' AND column_name='message_type_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_messages DROP COLUMN enquiry_type_code','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_messages' AND column_name='enquiry_type_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_messages DROP COLUMN slug','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_messages' AND column_name='slug'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_messages DROP COLUMN created_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_messages' AND column_name='created_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_messages DROP COLUMN updated_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_messages' AND column_name='updated_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

