-- phpMyAdmin-safe hybrid cleanup for suppliers/products (no procedures, no delimiters)

/* syntec_suppliers */
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_suppliers DROP COLUMN id','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_suppliers' AND column_name='id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_suppliers DROP COLUMN supplier_code','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_suppliers' AND column_name='supplier_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_suppliers DROP COLUMN name','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_suppliers' AND column_name='name'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_suppliers DROP COLUMN short_description','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_suppliers' AND column_name='short_description'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_suppliers DROP COLUMN website_url','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_suppliers' AND column_name='website_url'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_suppliers DROP COLUMN logo_path','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_suppliers' AND column_name='logo_path'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_suppliers DROP COLUMN banner_path','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_suppliers' AND column_name='banner_path'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_suppliers DROP COLUMN business_unit','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_suppliers' AND column_name='business_unit'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_suppliers DROP COLUMN slug','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_suppliers' AND column_name='slug'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_suppliers DROP COLUMN sort_order','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_suppliers' AND column_name='sort_order'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_suppliers DROP COLUMN active_flag','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_suppliers' AND column_name='active_flag'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_suppliers DROP COLUMN created_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_suppliers' AND column_name='created_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_suppliers DROP COLUMN updated_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_suppliers' AND column_name='updated_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

/* syntec_products */
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN id','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN product_code','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='product_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN sku','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='sku'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN name','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='name'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN short_description','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='short_description'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN long_description','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='long_description'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN category_summary','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='category_summary'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN primary_image_path','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='primary_image_path'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN external_url','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='external_url'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN oracle_product_id','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='oracle_product_id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN oracle_supplier_code','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='oracle_supplier_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN slug','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='slug'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN sort_order','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='sort_order'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN active_flag','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='active_flag'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN created_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='created_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN updated_at','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='updated_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(COUNT(*)=1,'ALTER TABLE syntec_products DROP COLUMN supplier_name_lookup','SELECT 1') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='syntec_products' AND column_name='supplier_name_lookup'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

